# Generated by Django 5.0.6 on 2026-05-08 16:46

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollateralType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "eligible_basel",
                    models.BooleanField(
                        default=False, help_text="Éligible au sens Bâle (HQLA, etc.)"
                    ),
                ),
                (
                    "haircut_pct",
                    models.FloatField(default=0.0, help_text="Décote (haircut) en %."),
                ),
                (
                    "liquidity_level",
                    models.CharField(
                        choices=[
                            ("level1", "Niveau 1"),
                            ("level2a", "Niveau 2A"),
                            ("level2b", "Niveau 2B"),
                            ("non_hqla", "Non-HQLA"),
                        ],
                        default="non_hqla",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Type de collatéral",
                "ordering": ["liquidity_level", "code"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code ISO 4217 (ex: XAF, EUR, USD).",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                (
                    "is_base",
                    models.BooleanField(
                        default=False, help_text="Devise pivot du bilan (ex: XAF)."
                    ),
                ),
                ("decimals", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("is_retail", models.BooleanField(default=False)),
                ("is_corporate", models.BooleanField(default=False)),
                ("is_financial", models.BooleanField(default=False)),
                (
                    "risk_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Pondération risque (0–1) appliquée pour LCR.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Segment client",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RepricingBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("label", models.CharField(max_length=64)),
                ("days_min", models.IntegerField(help_text="Borne basse (jours)")),
                (
                    "days_max",
                    models.IntegerField(
                        blank=True, help_text="Borne haute (jours, null = ∞)", null=True
                    ),
                ),
                (
                    "midpoint_days",
                    models.IntegerField(
                        help_text="Point milieu utilisé pour la duration"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Bucket de repricing",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                (
                    "consolidation",
                    models.CharField(
                        choices=[
                            ("full", "Intégration globale"),
                            ("proportional", "Intégration proportionnelle"),
                            ("equity", "Mise en équivalence"),
                            ("none", "Hors consolidation"),
                        ],
                        default="full",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mapping.currency",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="mapping.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entité",
                "verbose_name_plural": "Entités",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("region", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="mapping.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agence",
                "verbose_name_plural": "Agences",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCurrency",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code ISO 4217 (ex: XAF, EUR, USD).",
                        max_length=3,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                (
                    "is_base",
                    models.BooleanField(
                        default=False, help_text="Devise pivot du bilan (ex: XAF)."
                    ),
                ),
                ("decimals", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Devise",
                "verbose_name_plural": "historical Devises",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEntity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32)),
                ("label", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                (
                    "consolidation",
                    models.CharField(
                        choices=[
                            ("full", "Intégration globale"),
                            ("proportional", "Intégration proportionnelle"),
                            ("equity", "Mise en équivalence"),
                            ("none", "Hors consolidation"),
                        ],
                        default="full",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="mapping.currency",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="mapping.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Entité",
                "verbose_name_plural": "historical Entités",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOffBalanceCommitment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("credit_line", "Ligne de crédit confirmée"),
                            ("undrawn_facility", "Facilité non tirée"),
                            ("guarantee", "Garantie / caution"),
                            ("loc", "Lettre de crédit"),
                            ("derivative", "Engagement dérivé"),
                            ("other", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notional", models.BigIntegerField()),
                (
                    "drawdown_pct",
                    models.FloatField(
                        default=0.0,
                        help_text="Probabilité de tirage retenue pour le LCR / NSFR (%).",
                    ),
                ),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="mapping.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="mapping.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Engagement hors-bilan",
                "verbose_name_plural": "historical Engagement hors-bilans",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProductMapping",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("calypso", "Calypso"),
                            ("flexcube", "Flexcube"),
                            ("ledger", "Grand livre"),
                            ("manual", "Saisie manuelle"),
                            ("other", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "target_kind",
                    models.CharField(
                        help_text="Type d'input ALM cible (ex: credit, depot_terme, ...)",
                        max_length=64,
                    ),
                ),
                (
                    "target_subcategory",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "repricing_bucket",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "behavioral_tag",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Mapping produit",
                "verbose_name_plural": "historical Mappings produits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OffBalanceCommitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("credit_line", "Ligne de crédit confirmée"),
                            ("undrawn_facility", "Facilité non tirée"),
                            ("guarantee", "Garantie / caution"),
                            ("loc", "Lettre de crédit"),
                            ("derivative", "Engagement dérivé"),
                            ("other", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notional", models.BigIntegerField()),
                (
                    "drawdown_pct",
                    models.FloatField(
                        default=0.0,
                        help_text="Probabilité de tirage retenue pour le LCR / NSFR (%).",
                    ),
                ),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mapping.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mapping.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement hors-bilan",
                "ordering": ["type", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("calypso", "Calypso"),
                            ("flexcube", "Flexcube"),
                            ("ledger", "Grand livre"),
                            ("manual", "Saisie manuelle"),
                            ("other", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "target_kind",
                    models.CharField(
                        help_text="Type d'input ALM cible (ex: credit, depot_terme, ...)",
                        max_length=64,
                    ),
                ),
                (
                    "target_subcategory",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "repricing_bucket",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "behavioral_tag",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mapping produit",
                "verbose_name_plural": "Mappings produits",
                "ordering": ["source_system", "source_code"],
                "unique_together": {("source_system", "source_code")},
            },
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "rate",
                    models.FloatField(
                        help_text="Taux 1 unité de currency = rate × devise pivot."
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, default="manual", max_length=64),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="mapping.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("currency", "date")},
            },
        ),
    ]
