# Generated by Django 5.0.6 on 2026-05-08 16:46

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identifiant logique (ex: nmd_stable_compte_372).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nmd_stability", "Stabilité des NMD"),
                            ("prepayment", "Remboursement anticipé"),
                            ("withdrawal", "Retrait anticipé"),
                            ("rollover", "Roll-over"),
                            ("embedded_option", "Option embarquée"),
                            ("ftp_curve", "Courbe FTP"),
                            ("stress_scenario", "Scénario de stress"),
                            ("rate_shock", "Choc de taux"),
                            ("custom", "Personnalisée"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "methodology",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description de la méthodologie utilisée pour calibrer la valeur.",
                    ),
                ),
                (
                    "sources",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Sources de données utilisées (historique, études, etc.).",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Propriétaire métier de l'hypothèse.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_assumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hypothèse",
                "verbose_name_plural": "Hypothèses",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAssumptionVersion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("value", models.FloatField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon (maker)"),
                            ("review", "En revue (checker)"),
                            ("approved", "Approuvé"),
                            ("active", "Actif"),
                            ("retired", "Retiré"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        blank=True, default="", help_text="Justification du changement."
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assumption",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="governance.assumption",
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Version d'hypothèse",
                "verbose_name_plural": "historical Versions d'hypothèses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalScenarioLibrary",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("liquidity", "Liquidité"),
                            ("interest_rate", "Taux d'intérêt"),
                            ("combined", "Combiné"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paramètres du scénario (chocs, déplacements de courbe, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Scénario",
                "verbose_name_plural": "historical Bibliothèque de scénarios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ScenarioLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("liquidity", "Liquidité"),
                            ("interest_rate", "Taux d'intérêt"),
                            ("combined", "Combiné"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paramètres du scénario (chocs, déplacements de courbe, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scénario",
                "verbose_name_plural": "Bibliothèque de scénarios",
                "ordering": ["scope", "code"],
            },
        ),
        migrations.CreateModel(
            name="AssumptionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("value", models.FloatField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Brouillon (maker)"),
                            ("review", "En revue (checker)"),
                            ("approved", "Approuvé"),
                            ("active", "Actif"),
                            ("retired", "Retiré"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        blank=True, default="", help_text="Justification du changement."
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_assumption_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="governance.assumption",
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_assumption_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_assumption_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Version d'hypothèse",
                "verbose_name_plural": "Versions d'hypothèses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["assumption", "state"],
                        name="governance__assumpt_ca3c73_idx",
                    )
                ],
                "unique_together": {("assumption", "version_number")},
            },
        ),
    ]
