# Generated by Django 5.0.6 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assumption",
            name="impacted_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Modules et rapports impactés par l'hypothèse.",
            ),
        ),
        migrations.AddField(
            model_name="assumption",
            name="calculation_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Explication métier de l'utilisation de l'hypothèse dans les calculs.",
            ),
        ),
        migrations.AddField(
            model_name="assumption",
            name="requires_approval",
            field=models.BooleanField(
                default=True,
                help_text="Impose le circuit maker-checker avant activation opérationnelle.",
            ),
        ),
    ]
