# Generated by Django 5.2.15 on 2026-06-03 16:36

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOffBalanceSheetItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_arrete', models.DateField(db_index=True)),
                ('type_engagement', models.CharField(choices=[('ligne_credit', 'Ligne de crédit confirmée'), ('garantie', 'Garantie émise'), ('lettre_credit', 'Lettre de crédit (LC)'), ('engagement_fin', 'Engagement de financement'), ('swap', 'Swap de taux / change'), ('lfp', 'Ligne de financement potentielle (LFP)'), ('autre', 'Autre engagement')], max_length=32)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('segment', models.CharField(blank=True, default='', max_length=64)),
                ('secteur', models.CharField(blank=True, default='', max_length=64)),
                ('business_unit', models.CharField(blank=True, default='', max_length=64)),
                ('entite', models.CharField(blank=True, default='', max_length=64)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('notionnel', models.BigIntegerField(default=0, help_text="Montant notionnel total de l'engagement.")),
                ('montant_utilise', models.BigIntegerField(default=0, help_text='Montant déjà utilisé/tiré.')),
                ('prob_tirage_pct', models.FloatField(default=100.0, help_text='Probabilité de tirage en % (utilisée pour pondérer dans le gap liquidité et LCR).')),
                ('taux', models.FloatField(default=0.0, help_text="Taux d'intérêt ou de swap (%).")),
                ('type_taux', models.CharField(choices=[('fixe', 'Fixe'), ('variable', 'Variable'), ('administre', 'Administré'), ('indexe', 'Indexé'), ('revisable', 'Révisable')], default='fixe', max_length=16)),
                ('date_mise_place', models.DateField(blank=True, null=True)),
                ('maturite', models.DateField(blank=True, null=True)),
                ('bucket_liquidite', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(default='flexcube', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Engagement hors-bilan',
                'verbose_name_plural': 'historical Engagements hors-bilan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OffBalanceSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrete', models.DateField(db_index=True)),
                ('type_engagement', models.CharField(choices=[('ligne_credit', 'Ligne de crédit confirmée'), ('garantie', 'Garantie émise'), ('lettre_credit', 'Lettre de crédit (LC)'), ('engagement_fin', 'Engagement de financement'), ('swap', 'Swap de taux / change'), ('lfp', 'Ligne de financement potentielle (LFP)'), ('autre', 'Autre engagement')], max_length=32)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('segment', models.CharField(blank=True, default='', max_length=64)),
                ('secteur', models.CharField(blank=True, default='', max_length=64)),
                ('business_unit', models.CharField(blank=True, default='', max_length=64)),
                ('entite', models.CharField(blank=True, default='', max_length=64)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('notionnel', models.BigIntegerField(default=0, help_text="Montant notionnel total de l'engagement.")),
                ('montant_utilise', models.BigIntegerField(default=0, help_text='Montant déjà utilisé/tiré.')),
                ('prob_tirage_pct', models.FloatField(default=100.0, help_text='Probabilité de tirage en % (utilisée pour pondérer dans le gap liquidité et LCR).')),
                ('taux', models.FloatField(default=0.0, help_text="Taux d'intérêt ou de swap (%).")),
                ('type_taux', models.CharField(choices=[('fixe', 'Fixe'), ('variable', 'Variable'), ('administre', 'Administré'), ('indexe', 'Indexé'), ('revisable', 'Révisable')], default='fixe', max_length=16)),
                ('date_mise_place', models.DateField(blank=True, null=True)),
                ('maturite', models.DateField(blank=True, null=True)),
                ('bucket_liquidite', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(default='flexcube', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Engagement hors-bilan',
                'verbose_name_plural': 'Engagements hors-bilan',
                'ordering': ['-date_arrete', 'type_engagement'],
                'indexes': [models.Index(fields=['date_arrete', 'type_engagement'], name='off_balance_date_ar_bce72f_idx'), models.Index(fields=['date_arrete', 'devise'], name='off_balance_date_ar_ca7cab_idx')],
            },
        ),
    ]
