# Generated by Django 5.0.6 on 2026-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_reportannotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportannotation",
            name="section",
            field=models.CharField(
                choices=[
                    ("synthesis", "Synthèse liquidité"),
                    ("lcr", "Liquidity Coverage Ratio"),
                    ("rate_gap", "Gap de taux"),
                    ("nii", "NII Sensitivity"),
                    ("eve", "EVE Sensitivity"),
                    ("eve_enriched", "EVE enrichi"),
                    ("scenario_analysis", "Scenario Analysis"),
                    ("concentration", "Concentration"),
                    ("concentration_enriched", "Concentration enrichie"),
                    ("multicurrency", "Multi-devises"),
                    ("balance_sheet", "Bilan complet"),
                    ("fx_position", "Position FX"),
                    ("custom", "Personnalisé"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
