# Generated by Django 5.0.6 on 2026-05-08 16:46

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InputAvanceBeac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("montant", models.IntegerField()),
                ("date_valeur", models.DateTimeField()),
                ("echeance", models.DateTimeField()),
                ("taux", models.FloatField()),
                ("interets", models.BigIntegerField()),
                ("montant_total_rembourse", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Avance BEAC",
                "verbose_name_plural": "Avances BEAC",
            },
        ),
        migrations.CreateModel(
            name="InputBeac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Compte BEAC",
                "verbose_name_plural": "Comptes BEAC",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InputBillet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Billets et pièces",
                "verbose_name_plural": "Billets et pièces",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InputBonCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("reference", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("compte_client", models.CharField(max_length=11)),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("montant", models.BigIntegerField()),
                ("taux", models.FloatField()),
                ("periodicite", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Bon de caisse",
                "verbose_name_plural": "Bons de caisse",
            },
        ),
        migrations.CreateModel(
            name="InputBta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("nom_client", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_valeur", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
                ("maturite", models.DateTimeField()),
                ("per_paiement", models.CharField(max_length=255)),
                ("taux_int", models.FloatField()),
            ],
            options={
                "verbose_name": "BTA",
                "verbose_name_plural": "BTA",
            },
        ),
        migrations.CreateModel(
            name="InputCompteCheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Compte chèque 372",
                "verbose_name_plural": "Comptes chèques 372",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InputCompteCourant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Compte courant 371",
                "verbose_name_plural": "Comptes courants 371",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InputCompteLivret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Compte livret 373",
                "verbose_name_plural": "Comptes livrets 373",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InputCpteCorr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Compte correspondant",
                "verbose_name_plural": "Comptes correspondants",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InputCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code_agence", models.CharField(max_length=5)),
                ("num_dossier", models.CharField(max_length=6)),
                ("raci", models.CharField(max_length=6)),
                ("avenant", models.BigIntegerField()),
                ("date_mep", models.DateTimeField()),
                ("date_prem_echeance", models.DateTimeField()),
                ("date_deu_echeance", models.DateTimeField()),
                ("nbre_echeance", models.IntegerField()),
                ("taux_interet", models.FloatField()),
                ("capital_restant", models.BigIntegerField()),
                ("montant_debloque", models.BigIntegerField()),
                ("frequence", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Crédit",
                "verbose_name_plural": "Crédits",
                "ordering": ["-date_mep"],
            },
        ),
        migrations.CreateModel(
            name="InputDecouvert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("agence", models.CharField(max_length=5)),
                ("naut", models.CharField(max_length=6)),
                ("code_client", models.CharField(max_length=11)),
                ("montant", models.BigIntegerField()),
                ("data_mise_place", models.DateTimeField()),
                ("taux_auto", models.FloatField()),
                ("plafond", models.BigIntegerField()),
                ("taux_dela_plafond", models.FloatField()),
                ("duree", models.IntegerField()),
                ("date_fin", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Découvert",
                "verbose_name_plural": "Découverts",
            },
        ),
        migrations.CreateModel(
            name="InputDepotTerme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("reference", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("compte_client", models.CharField(max_length=11)),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("montant", models.BigIntegerField()),
                ("taux_interet", models.FloatField()),
                ("periodicite", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Dépôt à terme",
                "verbose_name_plural": "Dépôts à terme",
            },
        ),
        migrations.CreateModel(
            name="InputEmpruntInter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("type", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_mise_place", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("echance", models.DateTimeField()),
                ("jour_echeance", models.IntegerField()),
                ("taux_interet", models.FloatField()),
            ],
            options={
                "verbose_name": "Emprunt interbancaire à blanc",
                "verbose_name_plural": "Emprunts interbancaires à blanc",
            },
        ),
        migrations.CreateModel(
            name="InputEmpruntInterBanc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("date_dern_paiement", models.DateTimeField()),
                ("date_pro_echeance", models.DateTimeField()),
                ("encours", models.CharField(max_length=255)),
                ("principal", models.BigIntegerField()),
                ("interet", models.BigIntegerField()),
                ("frequence_paiement", models.CharField(max_length=255)),
                ("taux", models.FloatField()),
            ],
            options={
                "verbose_name": "Emprunt interbancaire",
                "verbose_name_plural": "Emprunts interbancaires",
            },
        ),
        migrations.CreateModel(
            name="InputEmpruntObl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("devise", models.CharField(max_length=255)),
                ("nom_client", models.CharField(max_length=255)),
                ("code_emission", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("date_valeur", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
                ("maturite", models.DateTimeField()),
                ("taux_int", models.FloatField()),
            ],
            options={
                "verbose_name": "Emprunt obligataire",
                "verbose_name_plural": "Emprunts obligataires",
            },
        ),
        migrations.CreateModel(
            name="InputEmpruntTitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("contrepartie", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_valeur", models.DateTimeField()),
                ("echeance", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("taux", models.FloatField()),
                ("interet", models.BigIntegerField()),
                ("tva", models.BigIntegerField()),
                ("montant_total_rembourse", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Emprunt titre",
                "verbose_name_plural": "Emprunts titres",
            },
        ),
        migrations.CreateModel(
            name="InputOta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code_emission", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_valeur", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
                ("maturite", models.DateTimeField()),
                ("taux_int", models.FloatField()),
            ],
            options={
                "verbose_name": "OTA",
                "verbose_name_plural": "OTA",
            },
        ),
        migrations.CreateModel(
            name="InputPensionLivree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("type", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_mise_place", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("echeance", models.DateTimeField()),
                ("jour_echeance", models.IntegerField()),
                ("taux_interet", models.FloatField()),
            ],
            options={
                "verbose_name": "Pension livrée",
                "verbose_name_plural": "Pensions livrées",
            },
        ),
        migrations.CreateModel(
            name="InputPretCor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code_agence", models.CharField(max_length=5)),
                ("num_dossier", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("avenant", models.BigIntegerField()),
                ("date_mep", models.DateTimeField()),
                ("date_prem_echeance", models.DateTimeField()),
                ("date_dern_echeance", models.DateTimeField()),
                ("nbre_echeance", models.IntegerField()),
                ("montant", models.BigIntegerField()),
                ("taux_interet", models.FloatField()),
                ("capital_restant", models.BigIntegerField()),
                ("periodicite", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Prêt correspondant",
                "verbose_name_plural": "Prêts correspondants",
            },
        ),
        migrations.CreateModel(
            name="InputPretInterBanc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("racine", models.CharField(max_length=6)),
                ("devise", models.CharField(max_length=255)),
                ("contrepartie", models.CharField(max_length=255)),
                ("solde", models.BigIntegerField()),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("per_paiement", models.CharField(max_length=255)),
                ("taux_int", models.FloatField()),
            ],
            options={
                "verbose_name": "Prêt interbancaire à blanc",
                "verbose_name_plural": "Prêts interbancaires à blanc",
            },
        ),
        migrations.CreateModel(
            name="InputPretTitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("contrepartie", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_mise", models.DateTimeField()),
                ("date_echeance", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("taux_integer", models.FloatField()),
                ("interet", models.BigIntegerField()),
                ("tva", models.BigIntegerField()),
                ("montant_rembourser", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Prêt titre",
                "verbose_name_plural": "Prêts titres",
            },
        ),
        migrations.CreateModel(
            name="InputTabAmort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code_agence", models.CharField(max_length=5)),
                ("num_dossier", models.CharField(max_length=6)),
                ("avenant", models.BigIntegerField()),
                ("devise", models.CharField(max_length=255)),
                ("num_echeance", models.BigIntegerField()),
                ("date_echeance", models.DateTimeField()),
                ("amort_calcul", models.BigIntegerField()),
                ("montant_echeance", models.BigIntegerField()),
                ("statut_echeance", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tableau amortissement crédit",
                "verbose_name_plural": "Tableaux amortissement crédits",
            },
        ),
        migrations.CreateModel(
            name="InputTerme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("ref_cat", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("compte_client", models.CharField(max_length=11)),
                ("compte_cat", models.CharField(max_length=11)),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("montant", models.BigIntegerField()),
                ("periodicite", models.CharField(max_length=255)),
                ("taux_int", models.FloatField()),
            ],
            options={
                "verbose_name": "Prêt à terme",
                "verbose_name_plural": "Prêts à terme",
            },
        ),
        migrations.CreateModel(
            name="HistoricalInputAvanceBeac",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("montant", models.IntegerField()),
                ("date_valeur", models.DateTimeField()),
                ("echeance", models.DateTimeField()),
                ("taux", models.FloatField()),
                ("interets", models.BigIntegerField()),
                ("montant_total_rembourse", models.BigIntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Avance BEAC",
                "verbose_name_plural": "historical Avances BEAC",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputBeac",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Compte BEAC",
                "verbose_name_plural": "historical Comptes BEAC",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputBillet",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Billets et pièces",
                "verbose_name_plural": "historical Billets et pièces",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputBonCaisse",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("reference", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("compte_client", models.CharField(max_length=11)),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("montant", models.BigIntegerField()),
                ("taux", models.FloatField()),
                ("periodicite", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Bon de caisse",
                "verbose_name_plural": "historical Bons de caisse",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputBta",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("nom_client", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_valeur", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
                ("maturite", models.DateTimeField()),
                ("per_paiement", models.CharField(max_length=255)),
                ("taux_int", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical BTA",
                "verbose_name_plural": "historical BTA",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputCompteCheque",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Compte chèque 372",
                "verbose_name_plural": "historical Comptes chèques 372",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputCompteCourant",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Compte courant 371",
                "verbose_name_plural": "historical Comptes courants 371",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputCompteLivret",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Compte livret 373",
                "verbose_name_plural": "historical Comptes livrets 373",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputCpteCorr",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date", models.DateTimeField()),
                ("cumul", models.BigIntegerField()),
                ("tableauLog", models.FloatField(blank=True, null=True)),
                ("tableauVarLog", models.FloatField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Compte correspondant",
                "verbose_name_plural": "historical Comptes correspondants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputCredit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("code_agence", models.CharField(max_length=5)),
                ("num_dossier", models.CharField(max_length=6)),
                ("raci", models.CharField(max_length=6)),
                ("avenant", models.BigIntegerField()),
                ("date_mep", models.DateTimeField()),
                ("date_prem_echeance", models.DateTimeField()),
                ("date_deu_echeance", models.DateTimeField()),
                ("nbre_echeance", models.IntegerField()),
                ("taux_interet", models.FloatField()),
                ("capital_restant", models.BigIntegerField()),
                ("montant_debloque", models.BigIntegerField()),
                ("frequence", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Crédit",
                "verbose_name_plural": "historical Crédits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputDecouvert",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("agence", models.CharField(max_length=5)),
                ("naut", models.CharField(max_length=6)),
                ("code_client", models.CharField(max_length=11)),
                ("montant", models.BigIntegerField()),
                ("data_mise_place", models.DateTimeField()),
                ("taux_auto", models.FloatField()),
                ("plafond", models.BigIntegerField()),
                ("taux_dela_plafond", models.FloatField()),
                ("duree", models.IntegerField()),
                ("date_fin", models.DateTimeField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Découvert",
                "verbose_name_plural": "historical Découverts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputDepotTerme",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("reference", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("compte_client", models.CharField(max_length=11)),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("montant", models.BigIntegerField()),
                ("taux_interet", models.FloatField()),
                ("periodicite", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Dépôt à terme",
                "verbose_name_plural": "historical Dépôts à terme",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputEmpruntInter",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("type", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_mise_place", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("echance", models.DateTimeField()),
                ("jour_echeance", models.IntegerField()),
                ("taux_interet", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Emprunt interbancaire à blanc",
                "verbose_name_plural": "historical Emprunts interbancaires à blanc",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputEmpruntInterBanc",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date_dern_paiement", models.DateTimeField()),
                ("date_pro_echeance", models.DateTimeField()),
                ("encours", models.CharField(max_length=255)),
                ("principal", models.BigIntegerField()),
                ("interet", models.BigIntegerField()),
                ("frequence_paiement", models.CharField(max_length=255)),
                ("taux", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Emprunt interbancaire",
                "verbose_name_plural": "historical Emprunts interbancaires",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputEmpruntObl",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("devise", models.CharField(max_length=255)),
                ("nom_client", models.CharField(max_length=255)),
                ("code_emission", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("date_valeur", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
                ("maturite", models.DateTimeField()),
                ("taux_int", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Emprunt obligataire",
                "verbose_name_plural": "historical Emprunts obligataires",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputEmpruntTitre",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("contrepartie", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_valeur", models.DateTimeField()),
                ("echeance", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("taux", models.FloatField()),
                ("interet", models.BigIntegerField()),
                ("tva", models.BigIntegerField()),
                ("montant_total_rembourse", models.BigIntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Emprunt titre",
                "verbose_name_plural": "historical Emprunts titres",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputOta",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("code_emission", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_valeur", models.DateTimeField()),
                ("solde", models.BigIntegerField()),
                ("maturite", models.DateTimeField()),
                ("taux_int", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical OTA",
                "verbose_name_plural": "historical OTA",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputPensionLivree",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("type", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_mise_place", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("echeance", models.DateTimeField()),
                ("jour_echeance", models.IntegerField()),
                ("taux_interet", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pension livrée",
                "verbose_name_plural": "historical Pensions livrées",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputPretCor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("code_agence", models.CharField(max_length=5)),
                ("num_dossier", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("avenant", models.BigIntegerField()),
                ("date_mep", models.DateTimeField()),
                ("date_prem_echeance", models.DateTimeField()),
                ("date_dern_echeance", models.DateTimeField()),
                ("nbre_echeance", models.IntegerField()),
                ("montant", models.BigIntegerField()),
                ("taux_interet", models.FloatField()),
                ("capital_restant", models.BigIntegerField()),
                ("periodicite", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Prêt correspondant",
                "verbose_name_plural": "historical Prêts correspondants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputPretInterBanc",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("racine", models.CharField(max_length=6)),
                ("devise", models.CharField(max_length=255)),
                ("contrepartie", models.CharField(max_length=255)),
                ("solde", models.BigIntegerField()),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("per_paiement", models.CharField(max_length=255)),
                ("taux_int", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Prêt interbancaire à blanc",
                "verbose_name_plural": "historical Prêts interbancaires à blanc",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputPretTitre",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("contrepartie", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("montant", models.BigIntegerField()),
                ("date_mise", models.DateTimeField()),
                ("date_echeance", models.DateTimeField()),
                ("duree", models.IntegerField()),
                ("taux_integer", models.FloatField()),
                ("interet", models.BigIntegerField()),
                ("tva", models.BigIntegerField()),
                ("montant_rembourser", models.BigIntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Prêt titre",
                "verbose_name_plural": "historical Prêts titres",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputTabAmort",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("code_agence", models.CharField(max_length=5)),
                ("num_dossier", models.CharField(max_length=6)),
                ("avenant", models.BigIntegerField()),
                ("devise", models.CharField(max_length=255)),
                ("num_echeance", models.BigIntegerField()),
                ("date_echeance", models.DateTimeField()),
                ("amort_calcul", models.BigIntegerField()),
                ("montant_echeance", models.BigIntegerField()),
                ("statut_echeance", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tableau amortissement crédit",
                "verbose_name_plural": "historical Tableaux amortissement crédits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInputTerme",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("ref_cat", models.CharField(max_length=6)),
                ("racine", models.CharField(max_length=6)),
                ("compte_client", models.CharField(max_length=11)),
                ("compte_cat", models.CharField(max_length=11)),
                ("date_mep", models.DateTimeField()),
                ("maturite", models.DateTimeField()),
                ("montant", models.BigIntegerField()),
                ("periodicite", models.CharField(max_length=255)),
                ("taux_int", models.FloatField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Prêt à terme",
                "verbose_name_plural": "historical Prêts à terme",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Output",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("type_output", models.CharField(db_index=True, max_length=255)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("montant", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Output",
                "verbose_name_plural": "Outputs",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["type_output", "-date"],
                        name="inputs_outp_type_ou_adeb50_idx",
                    )
                ],
            },
        ),
    ]
