# Generated by Django 5.2.15 on 2026-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinputavancebeac',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputavancebeac',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputavancebeac',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputavancebeac',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputbeac',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputbeac',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputbeac',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputbeac',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputbillet',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputbillet',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputbillet',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputbillet',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputboncaisse',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputboncaisse',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputboncaisse',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputboncaisse',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputbta',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputbta',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputbta',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputbta',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecheque',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecheque',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecheque',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecheque',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecourant',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecourant',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecourant',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcomptecourant',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputcomptelivret',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcomptelivret',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputcomptelivret',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcomptelivret',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputcptecorr',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcptecorr',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputcptecorr',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcptecorr',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputcredit',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcredit',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputcredit',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputcredit',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputdecouvert',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputdecouvert',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputdecouvert',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputdecouvert',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputdepotterme',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputdepotterme',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputdepotterme',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputdepotterme',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinter',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinter',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinter',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinter',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinterbanc',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinterbanc',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinterbanc',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputempruntinterbanc',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputempruntobl',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputempruntobl',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputempruntobl',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputemprunttitre',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputemprunttitre',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputemprunttitre',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputemprunttitre',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputota',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputota',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputota',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputota',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputpensionlivree',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputpensionlivree',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputpensionlivree',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputpensionlivree',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputpretcor',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputpretcor',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputpretcor',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputpretcor',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputpretinterbanc',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputpretinterbanc',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputpretinterbanc',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputprettitre',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputprettitre',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputprettitre',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputprettitre',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputtabamort',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputtabamort',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputtabamort',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='historicalinputterme',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputterme',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalinputterme',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalinputterme',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputavancebeac',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputavancebeac',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputavancebeac',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputavancebeac',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputbeac',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputbeac',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputbeac',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputbeac',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputbillet',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputbillet',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputbillet',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputbillet',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputboncaisse',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputboncaisse',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputboncaisse',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputboncaisse',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputbta',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputbta',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputbta',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputbta',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputcomptecheque',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcomptecheque',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputcomptecheque',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcomptecheque',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputcomptecourant',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcomptecourant',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputcomptecourant',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcomptecourant',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputcomptelivret',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcomptelivret',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputcomptelivret',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcomptelivret',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='administre', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputcptecorr',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcptecorr',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputcptecorr',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcptecorr',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputcredit',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcredit',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputcredit',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputcredit',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputdecouvert',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputdecouvert',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputdecouvert',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputdecouvert',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputdepotterme',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputdepotterme',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputdepotterme',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputdepotterme',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputempruntinter',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputempruntinter',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputempruntinter',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputempruntinter',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputempruntinterbanc',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputempruntinterbanc',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputempruntinterbanc',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputempruntinterbanc',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputempruntobl',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputempruntobl',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputempruntobl',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputemprunttitre',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputemprunttitre',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputemprunttitre',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputemprunttitre',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputota',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputota',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputota',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputota',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputpensionlivree',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputpensionlivree',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputpensionlivree',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputpensionlivree',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputpretcor',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputpretcor',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputpretcor',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputpretcor',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputpretinterbanc',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputpretinterbanc',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputpretinterbanc',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputprettitre',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputprettitre',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputprettitre',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputprettitre',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputtabamort',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputtabamort',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputtabamort',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AddField(
            model_name='inputterme',
            name='business_unit',
            field=models.CharField(blank=True, default='', help_text='Business Unit / Direction (ex: Retail, Corporate, Trésorerie, Institutionnel).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputterme',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AddField(
            model_name='inputterme',
            name='secteur',
            field=models.CharField(blank=True, default='', help_text='Secteur économique du client (classification NACE ou locale).', max_length=64),
        ),
        migrations.AddField(
            model_name='inputterme',
            name='type_taux',
            field=models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', help_text="Type de taux d'intérêt — utilisé pour l'analyse du basis risk.", max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalinputempruntobl',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalinputpretinterbanc',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalinputtabamort',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AlterField(
            model_name='inputempruntobl',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AlterField(
            model_name='inputpretinterbanc',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
        migrations.AlterField(
            model_name='inputtabamort',
            name='devise',
            field=models.CharField(default='XAF', help_text='Code ISO 4217 de la devise (ex: XAF, EUR, USD). Alimenté depuis Flexcube champ CCY.', max_length=3),
        ),
    ]
