# Generated by Django 5.2.15 on 2026-06-03 18:53

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, help_text='Identifiant client Flexcube (CUSTOMER_NO).', max_length=32, unique=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_unit', models.CharField(blank=True, default='', help_text='Direction / BU responsable du client (ex: Retail Banking, Corporate, Trésorerie).', max_length=64)),
                ('segment', models.CharField(choices=[('retail', 'Retail / Particulier'), ('sme', 'PME'), ('corporate', 'Corporate'), ('public', 'Secteur public / Institutionnel'), ('financial', 'Institutions financières'), ('other', 'Autre')], default='other', help_text='Segment client principal.', max_length=32)),
                ('sous_segment', models.CharField(blank=True, choices=[('salarie', 'Salarié'), ('professionnel', 'Professionnel / Indépendant'), ('etudiant', 'Étudiant'), ('tpe', 'TPE (< 5 salariés)'), ('pme', 'PME (5-250 salariés)'), ('eti', 'ETI (250-5000 salariés)'), ('grande_entreprise', 'Grande Entreprise (> 5000 salariés)'), ('etat', 'État / Administrations centrales'), ('collectivite', 'Collectivités territoriales'), ('etablissement_public', 'Établissements publics'), ('ong', 'ONG / Associations'), ('banque', 'Banque'), ('assurance', 'Assurance'), ('microfinance', 'Microfinance'), ('fonds', 'Fonds / Asset Manager'), ('other', 'Autre')], default='', help_text='Sous-segment (granularité fine).', max_length=32)),
                ('secteur', models.CharField(blank=True, default='', help_text='Secteur économique (classification NACE, BEAC ou locale).', max_length=64)),
                ('secteur_code', models.CharField(blank=True, default='', help_text='Code numérique du secteur (ex: NACE A01, B05...).', max_length=16)),
                ('agence', models.CharField(blank=True, default='', max_length=16)),
                ('entite', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', help_text='Source : manual, flexcube, import_excel.', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapping client MIS',
                'verbose_name_plural': 'Mappings clients MIS',
                'ordering': ['business_unit', 'segment', 'client_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalClientMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, help_text='Identifiant client Flexcube (CUSTOMER_NO).', max_length=32)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_unit', models.CharField(blank=True, default='', help_text='Direction / BU responsable du client (ex: Retail Banking, Corporate, Trésorerie).', max_length=64)),
                ('segment', models.CharField(choices=[('retail', 'Retail / Particulier'), ('sme', 'PME'), ('corporate', 'Corporate'), ('public', 'Secteur public / Institutionnel'), ('financial', 'Institutions financières'), ('other', 'Autre')], default='other', help_text='Segment client principal.', max_length=32)),
                ('sous_segment', models.CharField(blank=True, choices=[('salarie', 'Salarié'), ('professionnel', 'Professionnel / Indépendant'), ('etudiant', 'Étudiant'), ('tpe', 'TPE (< 5 salariés)'), ('pme', 'PME (5-250 salariés)'), ('eti', 'ETI (250-5000 salariés)'), ('grande_entreprise', 'Grande Entreprise (> 5000 salariés)'), ('etat', 'État / Administrations centrales'), ('collectivite', 'Collectivités territoriales'), ('etablissement_public', 'Établissements publics'), ('ong', 'ONG / Associations'), ('banque', 'Banque'), ('assurance', 'Assurance'), ('microfinance', 'Microfinance'), ('fonds', 'Fonds / Asset Manager'), ('other', 'Autre')], default='', help_text='Sous-segment (granularité fine).', max_length=32)),
                ('secteur', models.CharField(blank=True, default='', help_text='Secteur économique (classification NACE, BEAC ou locale).', max_length=64)),
                ('secteur_code', models.CharField(blank=True, default='', help_text='Code numérique du secteur (ex: NACE A01, B05...).', max_length=16)),
                ('agence', models.CharField(blank=True, default='', max_length=16)),
                ('entite', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', help_text='Source : manual, flexcube, import_excel.', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mapping client MIS',
                'verbose_name_plural': 'historical Mappings clients MIS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
