# Generated by Django 5.0.6 on 2026-05-08 16:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passwordDelay", models.IntegerField(default=90)),
                ("delayActivate", models.BooleanField(default=True)),
                ("dateMajCore", models.DateTimeField(blank=True, null=True)),
                ("dateMajExtra", models.DateTimeField(blank=True, null=True)),
                (
                    "dateArrete",
                    models.DateTimeField(
                        blank=True, help_text="Date d'arrêté", null=True
                    ),
                ),
                ("commalcobase", models.TextField(blank=True, default="")),
                ("commalcomodere", models.TextField(blank=True, default="")),
                ("commalcosevere", models.TextField(blank=True, default="")),
                ("commdgbase", models.TextField(blank=True, default="")),
                ("commdgmodere", models.TextField(blank=True, default="")),
                ("commdgsevere", models.TextField(blank=True, default="")),
                ("beta_cheque", models.FloatField(blank=True, null=True)),
                ("beta_courant", models.FloatField(blank=True, null=True)),
                ("beta_livret", models.FloatField(blank=True, null=True)),
                ("beta_beac", models.FloatField(blank=True, null=True)),
                ("beta_corr", models.FloatField(blank=True, null=True)),
                ("stable_courant", models.FloatField(blank=True, null=True)),
                ("stable_cheque", models.FloatField(blank=True, null=True)),
                ("stable_livret", models.FloatField(blank=True, null=True)),
                ("stable_beac", models.FloatField(blank=True, null=True)),
                ("stable_corr", models.FloatField(blank=True, null=True)),
                ("var_courant", models.FloatField(blank=True, null=True)),
                ("var_cheque", models.FloatField(blank=True, null=True)),
                ("var_livret", models.FloatField(blank=True, null=True)),
                ("var_beac", models.FloatField(blank=True, null=True)),
                ("var_corr", models.FloatField(blank=True, null=True)),
                ("credMod", models.IntegerField(default=0)),
                ("credSev", models.IntegerField(default=0)),
                ("banMod", models.IntegerField(default=0)),
                ("banSev", models.IntegerField(default=0)),
                ("retMod", models.IntegerField(default=0)),
                ("retSev", models.IntegerField(default=0)),
                ("guiMod", models.IntegerField(default=0)),
                ("guiSev", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre",
                "verbose_name_plural": "Paramètres",
            },
        ),
        migrations.CreateModel(
            name="HistoricalParameter",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("passwordDelay", models.IntegerField(default=90)),
                ("delayActivate", models.BooleanField(default=True)),
                ("dateMajCore", models.DateTimeField(blank=True, null=True)),
                ("dateMajExtra", models.DateTimeField(blank=True, null=True)),
                (
                    "dateArrete",
                    models.DateTimeField(
                        blank=True, help_text="Date d'arrêté", null=True
                    ),
                ),
                ("commalcobase", models.TextField(blank=True, default="")),
                ("commalcomodere", models.TextField(blank=True, default="")),
                ("commalcosevere", models.TextField(blank=True, default="")),
                ("commdgbase", models.TextField(blank=True, default="")),
                ("commdgmodere", models.TextField(blank=True, default="")),
                ("commdgsevere", models.TextField(blank=True, default="")),
                ("beta_cheque", models.FloatField(blank=True, null=True)),
                ("beta_courant", models.FloatField(blank=True, null=True)),
                ("beta_livret", models.FloatField(blank=True, null=True)),
                ("beta_beac", models.FloatField(blank=True, null=True)),
                ("beta_corr", models.FloatField(blank=True, null=True)),
                ("stable_courant", models.FloatField(blank=True, null=True)),
                ("stable_cheque", models.FloatField(blank=True, null=True)),
                ("stable_livret", models.FloatField(blank=True, null=True)),
                ("stable_beac", models.FloatField(blank=True, null=True)),
                ("stable_corr", models.FloatField(blank=True, null=True)),
                ("var_courant", models.FloatField(blank=True, null=True)),
                ("var_cheque", models.FloatField(blank=True, null=True)),
                ("var_livret", models.FloatField(blank=True, null=True)),
                ("var_beac", models.FloatField(blank=True, null=True)),
                ("var_corr", models.FloatField(blank=True, null=True)),
                ("credMod", models.IntegerField(default=0)),
                ("credSev", models.IntegerField(default=0)),
                ("banMod", models.IntegerField(default=0)),
                ("banSev", models.IntegerField(default=0)),
                ("retMod", models.IntegerField(default=0)),
                ("retSev", models.IntegerField(default=0)),
                ("guiMod", models.IntegerField(default=0)),
                ("guiSev", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Paramètre",
                "verbose_name_plural": "historical Paramètres",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
