# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="bankName",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="parameter",
            name="bankLogo",
            field=models.FileField(blank=True, null=True, upload_to="bank_logos/"),
        ),
        migrations.AddField(
            model_name="historicalparameter",
            name="bankName",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicalparameter",
            name="bankLogo",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
