# Generated by Django 5.0.6 on 2026-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicenseState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(default="unconfigured", max_length=16)),
                (
                    "license_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("enabled_modules", models.JSONField(blank=True, default=list)),
                ("grace_period_days", models.IntegerField(default=30)),
                ("last_token", models.TextField(blank=True, default="")),
                ("last_token_iat", models.DateTimeField(blank=True, null=True)),
                ("last_contact_ok_at", models.DateTimeField(blank=True, null=True)),
                ("last_contact_error", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "État de licence",
            },
        ),
    ]
