# Generated by Django 5.0.6 on 2026-05-08 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "horodatage",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée d'audit",
                "verbose_name_plural": "Audit",
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(
                        fields=["-horodatage"], name="tracking_tr_horodat_d030d6_idx"
                    ),
                    models.Index(
                        fields=["libelle"], name="tracking_tr_libelle_205bdc_idx"
                    ),
                ],
            },
        ),
    ]
