# Generated by Django 5.2.15 on 2026-06-03 16:36

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrete', models.DateField(db_index=True, help_text="Date d'arrêté comptable.")),
                ('compte_gl', models.CharField(db_index=True, help_text='Numéro de compte GL (Flexcube AC_NO).', max_length=32)),
                ('libelle', models.CharField(help_text='Libellé du compte GL.', max_length=255)),
                ('product_code', models.CharField(blank=True, default='', help_text='Code produit Flexcube (PRODUCT_CODE).', max_length=64)),
                ('client_id', models.CharField(blank=True, default='', help_text='Identifiant client Flexcube (CUSTOMER_NO).', max_length=32)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_unit', models.CharField(blank=True, default='', help_text='Direction / BU (ex: Retail, Corporate, Trésorerie).', max_length=64)),
                ('segment', models.CharField(blank=True, default='', help_text='Segment client (retail, sme, corporate, public, financial).', max_length=64)),
                ('sous_segment', models.CharField(blank=True, default='', max_length=64)),
                ('secteur', models.CharField(blank=True, default='', help_text='Secteur économique (NACE ou classification locale).', max_length=64)),
                ('devise', models.CharField(default='XAF', help_text='Code ISO 4217 (Flexcube CCY).', max_length=3)),
                ('montant_lcy', models.BigIntegerField(default=0, help_text='Montant en devise locale (XAF).')),
                ('montant_fcy', models.BigIntegerField(default=0, help_text='Montant en devise étrangère (si FCY).')),
                ('sens', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('hors_bilan', 'Hors-bilan')], default='actif', max_length=12)),
                ('type_taux', models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', max_length=16)),
                ('taux_moyen', models.FloatField(default=0.0, help_text='Taux moyen pondéré appliqué à cette ligne (%).')),
                ('maturite', models.DateField(blank=True, help_text='Date de maturité contractuelle.', null=True)),
                ('bucket_liquidite', models.CharField(blank=True, default='', help_text='Code bucket de liquidité (calculé automatiquement).', max_length=32)),
                ('bucket_repricing', models.CharField(blank=True, default='', help_text='Code bucket de repricing.', max_length=32)),
                ('entite', models.CharField(blank=True, default='', help_text='Entité du groupe bancaire.', max_length=64)),
                ('agence', models.CharField(blank=True, default='', help_text='Code agence Flexcube (BRANCH_CODE).', max_length=16)),
                ('source', models.CharField(default='flexcube', help_text='Système source (flexcube, manuel, autre).', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ligne de bilan GL',
                'verbose_name_plural': 'Lignes de bilan GL',
                'ordering': ['-date_arrete', 'sens', 'compte_gl'],
                'indexes': [models.Index(fields=['date_arrete', 'sens'], name='balance_she_date_ar_192c1e_idx'), models.Index(fields=['date_arrete', 'devise'], name='balance_she_date_ar_d27e79_idx'), models.Index(fields=['date_arrete', 'business_unit'], name='balance_she_date_ar_0672d1_idx'), models.Index(fields=['compte_gl'], name='balance_she_compte__b22cad_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBalanceSheetLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_arrete', models.DateField(db_index=True, help_text="Date d'arrêté comptable.")),
                ('compte_gl', models.CharField(db_index=True, help_text='Numéro de compte GL (Flexcube AC_NO).', max_length=32)),
                ('libelle', models.CharField(help_text='Libellé du compte GL.', max_length=255)),
                ('product_code', models.CharField(blank=True, default='', help_text='Code produit Flexcube (PRODUCT_CODE).', max_length=64)),
                ('client_id', models.CharField(blank=True, default='', help_text='Identifiant client Flexcube (CUSTOMER_NO).', max_length=32)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_unit', models.CharField(blank=True, default='', help_text='Direction / BU (ex: Retail, Corporate, Trésorerie).', max_length=64)),
                ('segment', models.CharField(blank=True, default='', help_text='Segment client (retail, sme, corporate, public, financial).', max_length=64)),
                ('sous_segment', models.CharField(blank=True, default='', max_length=64)),
                ('secteur', models.CharField(blank=True, default='', help_text='Secteur économique (NACE ou classification locale).', max_length=64)),
                ('devise', models.CharField(default='XAF', help_text='Code ISO 4217 (Flexcube CCY).', max_length=3)),
                ('montant_lcy', models.BigIntegerField(default=0, help_text='Montant en devise locale (XAF).')),
                ('montant_fcy', models.BigIntegerField(default=0, help_text='Montant en devise étrangère (si FCY).')),
                ('sens', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('hors_bilan', 'Hors-bilan')], default='actif', max_length=12)),
                ('type_taux', models.CharField(choices=[('fixe', 'Taux fixe'), ('variable', 'Taux variable (marché)'), ('administre', 'Taux administré (BEAC/TIAO)'), ('indexe', 'Taux indexé (EURIBOR/SOFR)'), ('revisable', 'Taux révisable')], default='fixe', max_length=16)),
                ('taux_moyen', models.FloatField(default=0.0, help_text='Taux moyen pondéré appliqué à cette ligne (%).')),
                ('maturite', models.DateField(blank=True, help_text='Date de maturité contractuelle.', null=True)),
                ('bucket_liquidite', models.CharField(blank=True, default='', help_text='Code bucket de liquidité (calculé automatiquement).', max_length=32)),
                ('bucket_repricing', models.CharField(blank=True, default='', help_text='Code bucket de repricing.', max_length=32)),
                ('entite', models.CharField(blank=True, default='', help_text='Entité du groupe bancaire.', max_length=64)),
                ('agence', models.CharField(blank=True, default='', help_text='Code agence Flexcube (BRANCH_CODE).', max_length=16)),
                ('source', models.CharField(default='flexcube', help_text='Système source (flexcube, manuel, autre).', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ligne de bilan GL',
                'verbose_name_plural': 'historical Lignes de bilan GL',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
