# Generated by Django 5.0.6 on 2026-05-08 16:46

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyWithdrawalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("depot_terme", "Dépôt à terme"),
                            ("bon", "Bon de caisse"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "annual_rate_pct",
                    models.FloatField(help_text="Taux annuel de retrait anticipé (%)"),
                ),
                ("rate_sensitivity", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_models",
                        to="governance.assumptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de retrait anticipé",
                "ordering": ["product", "code"],
            },
        ),
        migrations.CreateModel(
            name="EmbeddedOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("cap", "Cap (taux plafond)"),
                            ("floor", "Floor (taux plancher)"),
                            ("call", "Call (option de remboursement émetteur)"),
                            ("put", "Put (option de remboursement détenteur)"),
                            ("conversion", "Option de conversion"),
                            ("other", "Autre"),
                        ],
                        max_length=16,
                    ),
                ),
                ("strike", models.FloatField(blank=True, null=True)),
                ("notional", models.BigIntegerField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedded_options",
                        to="governance.assumptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option embarquée",
                "verbose_name_plural": "Options embarquées",
            },
        ),
        migrations.CreateModel(
            name="HistoricalEarlyWithdrawalModel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("depot_terme", "Dépôt à terme"),
                            ("bon", "Bon de caisse"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "annual_rate_pct",
                    models.FloatField(help_text="Taux annuel de retrait anticipé (%)"),
                ),
                ("rate_sensitivity", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="governance.assumptionversion",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Modèle de retrait anticipé",
                "verbose_name_plural": "historical Modèle de retrait anticipés",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmbeddedOption",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("cap", "Cap (taux plafond)"),
                            ("floor", "Floor (taux plancher)"),
                            ("call", "Call (option de remboursement émetteur)"),
                            ("put", "Put (option de remboursement détenteur)"),
                            ("conversion", "Option de conversion"),
                            ("other", "Autre"),
                        ],
                        max_length=16,
                    ),
                ),
                ("strike", models.FloatField(blank=True, null=True)),
                ("notional", models.BigIntegerField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="governance.assumptionversion",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Option embarquée",
                "verbose_name_plural": "historical Options embarquées",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNmdModel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("compte_371", "Comptes courants 371"),
                            ("compte_372", "Comptes chèques 372"),
                            ("compte_373", "Comptes livrets 373"),
                            ("compte_vue_cor", "Comptes vue correspondants"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("retail", "Retail / Particulier"),
                            ("sme", "PME"),
                            ("corporate", "Corporate"),
                            ("public", "Secteur public"),
                            ("financial", "Institutions financières"),
                            ("all", "Tous segments"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                (
                    "core_stable_pct",
                    models.FloatField(help_text="Part stable cœur (%)"),
                ),
                (
                    "non_core_stable_pct",
                    models.FloatField(help_text="Part stable non-cœur (%)"),
                ),
                ("volatile_pct", models.FloatField(help_text="Part volatile (%)")),
                (
                    "runoff_core_months",
                    models.IntegerField(
                        default=60, help_text="Durée écoulement cœur (mois)"
                    ),
                ),
                ("runoff_non_core_months", models.IntegerField(default=24)),
                (
                    "repricing_lag_months",
                    models.IntegerField(
                        default=1,
                        help_text="Lag de repricing aux taux de marché (mois)",
                    ),
                ),
                (
                    "pass_through_pct",
                    models.FloatField(
                        default=50.0,
                        help_text="% de pass-through des taux de marché aux taux clients (β beta)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="governance.assumptionversion",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Modèle NMD",
                "verbose_name_plural": "historical Modèles NMD",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPrepaymentModel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("credit_consumer", "Crédit conso"),
                            ("credit_mortgage", "Crédit immobilier"),
                            ("credit_pro", "Crédit professionnel"),
                            ("credit_corporate", "Crédit corporate"),
                            ("credit_other", "Autre crédit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("cpr_annual", models.FloatField(help_text="CPR annuel (%)")),
                (
                    "rate_sensitivity",
                    models.FloatField(
                        default=0.0,
                        help_text="Sensibilité aux taux : variation du CPR par 100 bp de baisse de taux.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="governance.assumptionversion",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Modèle de remboursement anticipé",
                "verbose_name_plural": "historical Modèle de remboursement anticipés",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRolloverModel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=64)),
                (
                    "rollover_rate_pct",
                    models.FloatField(help_text="% de renouvellement à maturité"),
                ),
                (
                    "new_term_months",
                    models.IntegerField(help_text="Durée du nouveau contrat (mois)"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="governance.assumptionversion",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Modèle de roll-over",
                "verbose_name_plural": "historical Modèle de roll-overs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="NmdModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("compte_371", "Comptes courants 371"),
                            ("compte_372", "Comptes chèques 372"),
                            ("compte_373", "Comptes livrets 373"),
                            ("compte_vue_cor", "Comptes vue correspondants"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("retail", "Retail / Particulier"),
                            ("sme", "PME"),
                            ("corporate", "Corporate"),
                            ("public", "Secteur public"),
                            ("financial", "Institutions financières"),
                            ("all", "Tous segments"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                (
                    "core_stable_pct",
                    models.FloatField(help_text="Part stable cœur (%)"),
                ),
                (
                    "non_core_stable_pct",
                    models.FloatField(help_text="Part stable non-cœur (%)"),
                ),
                ("volatile_pct", models.FloatField(help_text="Part volatile (%)")),
                (
                    "runoff_core_months",
                    models.IntegerField(
                        default=60, help_text="Durée écoulement cœur (mois)"
                    ),
                ),
                ("runoff_non_core_months", models.IntegerField(default=24)),
                (
                    "repricing_lag_months",
                    models.IntegerField(
                        default=1,
                        help_text="Lag de repricing aux taux de marché (mois)",
                    ),
                ),
                (
                    "pass_through_pct",
                    models.FloatField(
                        default=50.0,
                        help_text="% de pass-through des taux de marché aux taux clients (β beta)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nmd_models",
                        to="governance.assumptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle NMD",
                "verbose_name_plural": "Modèles NMD",
                "ordering": ["product", "segment"],
            },
        ),
        migrations.CreateModel(
            name="PrepaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("credit_consumer", "Crédit conso"),
                            ("credit_mortgage", "Crédit immobilier"),
                            ("credit_pro", "Crédit professionnel"),
                            ("credit_corporate", "Crédit corporate"),
                            ("credit_other", "Autre crédit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("cpr_annual", models.FloatField(help_text="CPR annuel (%)")),
                (
                    "rate_sensitivity",
                    models.FloatField(
                        default=0.0,
                        help_text="Sensibilité aux taux : variation du CPR par 100 bp de baisse de taux.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepayment_models",
                        to="governance.assumptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de remboursement anticipé",
                "ordering": ["product", "code"],
            },
        ),
        migrations.CreateModel(
            name="RolloverModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=64)),
                (
                    "rollover_rate_pct",
                    models.FloatField(help_text="% de renouvellement à maturité"),
                ),
                (
                    "new_term_months",
                    models.IntegerField(help_text="Durée du nouveau contrat (mois)"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assumption_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollover_models",
                        to="governance.assumptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de roll-over",
                "ordering": ["product"],
            },
        ),
    ]
